"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const CreateMedicine_1 = require("../../Controllers/DepositController/Medicines/CreateMedicine");
const FindMedicine_1 = require("../../Controllers/DepositController/Medicines/FindMedicine");
const FindAllMedicines_1 = require("../../Controllers/DepositController/Medicines/FindAllMedicines");
const DepositRouter = (0, express_1.Router)();
DepositRouter.route("/medicamentos").post((req, res) => { CreateMedicine_1.CreateMedicineController.CreateMedicine(req, res); });
DepositRouter.route("/medicamento/:nome_comercial").post((req, res) => { FindMedicine_1.FindMedicineController.FindMedicine(req, res); });
DepositRouter.route("/medicamentos").get((req, res) => { FindAllMedicines_1.FindAllMedicinesController.FindMedicines(req, res); });
exports.default = DepositRouter;
